GET http://localhost:3000/status/health

###

GET http://localhost:3000/api/items

###

POST http://localhost:3000/api/items
Content-Type: application/json

{
 "name": "test-item",
 "description": "Experimenal",
 "date_origin": "2024-10-20T10:57:27Z"
}
